I_USER="k1max"
I_HOME="/home/k1max"
RH_PATH="/home/k1max/printer_data/config/reshelper"
CONFIG_PATH="/home/k1max/printer_data/config/reshelper"
KLIPPER_PATH="/home/k1max/klipper"
PK_PATH="/home/k1max/klippy-env/bin"
KLIPPER_VER="MAIN"
TMP_PATH="/tmp"